return {
    "AcceptTradeRequest",
    "AddFilterConveyorObject",
    "AddItemToTrade",
    "AddStructureToTrade",
    "AdminPanel",
    "AdminTeleportPromptResponse",
    "AnchorObject",
    "AskForBulkPurchase",
    "AskForGamepassPurchase",
    "AskForPurchase",
    "AskForVinyl",
    "AssignLogicId",
    "AssignLogicString",
    "AttachObject",
    "AttemptDetonate",
    "AttemptPurchase_Alan's Autologistics",
    "AttemptPurchase_Alien Shop",
    "AttemptPurchase_Bob_Fridman_Scene",
    "AttemptPurchase_Classic Store",
    "AttemptPurchase_Dugg's Digging",
    "AttemptPurchase_Flora Laura",
    "AttemptPurchase_Frost Store",
    "AttemptPurchase_Fungi Finds",
    "AttemptPurchase_Goblin Blacksmith",
    "AttemptPurchase_Goblin Merchant A",
    "AttemptPurchase_Goblin Merchant B",
    "AttemptPurchase_Goblin Merchant C",
    "AttemptPurchase_Goblin Merchant D",
    "AttemptPurchase_Goblin Sorcerer",
    "AttemptPurchase_Hole in One",
    "AttemptPurchase_Illumine",
    "AttemptPurchase_Jerry's Junk",
    "AttemptPurchase_Lighthouse",
    "AttemptPurchase_Magma Store",
    "AttemptPurchase_Mike's Mines",
    "AttemptPurchase_MyIslandCollab",
    "AttemptPurchase_Observatory",
    "AttemptPurchase_Pirate Ship",
    "AttemptPurchase_Radical Shack",
    "AttemptPurchase_Recycle Center",
    "AttemptPurchase_River Store",
    "AttemptPurchase_Sell Station",
    "AttemptPurchase_The Oak Depot",
    "AttemptPurchase_Weapons Shack",
    "AttemptSell_Junkyard",
    "AttemptSell_Junkyard_Scene",
    "AttemptSell_Recycle Center",
    "AttemptSell_River Store",
    "BackpackDropTool",
    "BackpackEquipTool",
    "BackpackSaveOrder",
    "BackpackTellServer",
    "BackpackUnequipTool",
    "BuyBasement",
    "BuyCablecarTicket",
    "BuyCalendarReward",
    "BuyDailyRewardItem",
    "BuyFreecamUpgrade",
    "BuyShopItem",
    "BuySign",
    "CallCablecar",
    "CanDonateTo",
    "CanStartAlienOrbQuest",
    "CanStartHolyGrailQuest",
    "CanTradeTo",
    "CancelPipePlacement",
    "CancelTrade",
    "CheckCanGift",
    "ChooseGameplayPath",
    "ClaimAllQuestRewards",
    "ClaimCalendarReward",
    "ClaimDailyReward",
    "ClaimGolfReward",
    "ClaimMyIslandRewards",
    "ClaimQuestRewards",
    "ClaimVialPuzzle",
    "ClearNoCollides",
    "ClearOwnership",
    "ClientTouchEvent",
    "CloneLogicData",
    "CodeRedeem",
    "CodeValidation",
    "ContentRequestList",
    "CreateFreecam",
    "CreateSlot",
    "CreateTrack",
    "CreateWirePlaceable",
    "DamageEnemy",
    "DefineDesignDocument",
    "DeleteFreecam",
    "DeleteMidi",
    "DeleteSlot",
    "DenyTradeRequest",
    "DestroyStructure",
    "DoFollowRequest",
    "DoGroupRequest",
    "DragPosition",
    "DropEquipment",
    "DropGift",
    "DropItem",
    "DropTool",
    "DynamicCodeListRequest",
    "ESPList",
    "EndPonderingTutorial",
    "EndTutorial",
    "EquipSign",
    "EquipTool",
    "EquipmentDrop",
    "EquipmentTellServer",
    "EquipmentToggle",
    "ExpandProperty",
    "ExpandSceneProperty",
    "ExplodeHelicopter",
    "FavoriteBase",
    "FavoriteEntry",
    "FavoriteSlot",
    "FetchActiveBan",
    "FetchMinimapPlayers",
    "FilterPlayerText",
    "FindSerial",
    "FulfillClientGoal",
    "GetAlienOrbQuestState",
    "GetAlienScrap",
    "GetAllSettings",
    "GetAvailableProperty",
    "GetBasePresets",
    "GetBlueprints",
    "GetCablecarLocation",
    "GetCalendar",
    "GetChatRank",
    "GetCurrentMayorState",
    "GetCurrentTrackedQuest",
    "GetDataStatus",
    "GetDynamicRegions",
    "GetFilterConveyorData",
    "GetFilteredPlate",
    "GetGoldBombsiteInfo",
    "GetHolyGrailActiveRequirement",
    "GetInventory",
    "GetItemsOnCounter_Alan's Autologistics",
    "GetItemsOnCounter_Alien Shop",
    "GetItemsOnCounter_Bob_Fridman_Scene",
    "GetItemsOnCounter_Classic Store",
    "GetItemsOnCounter_Dugg's Digging",
    "GetItemsOnCounter_Flora Laura",
    "GetItemsOnCounter_Frost Store",
    "GetItemsOnCounter_Fungi Finds",
    "GetItemsOnCounter_Goblin Blacksmith",
    "GetItemsOnCounter_Goblin Merchant A",
    "GetItemsOnCounter_Goblin Merchant B",
    "GetItemsOnCounter_Goblin Merchant C",
    "GetItemsOnCounter_Goblin Merchant D",
    "GetItemsOnCounter_Goblin Sorcerer",
    "GetItemsOnCounter_Hole in One",
    "GetItemsOnCounter_Illumine",
    "GetItemsOnCounter_Jerry's Junk",
    "GetItemsOnCounter_Junkyard",
    "GetItemsOnCounter_Lighthouse",
    "GetItemsOnCounter_Magma Store",
    "GetItemsOnCounter_Mike's Mines",
    "GetItemsOnCounter_MyIslandCollab",
    "GetItemsOnCounter_Observatory",
    "GetItemsOnCounter_Pirate Ship",
    "GetItemsOnCounter_Radical Shack",
    "GetItemsOnCounter_Recycle Center",
    "GetItemsOnCounter_River Store",
    "GetItemsOnCounter_Sell Station",
    "GetItemsOnCounter_The Oak Depot",
    "GetItemsOnCounter_Weapons Shack",
    "GetLeaderboardData",
    "GetLumiteCredits",
    "GetMidiSongs",
    "GetMoney",
    "GetPermissionsSetForPlayer",
    "GetPreviousGlobalMessages",
    "GetPropertyHole",
    "GetPropertyInfo",
    "GetPropertyLocationOffer",
    "GetPropertyPrice",
    "GetPropertyTerrainStyleState",
    "GetPropertyTerrainStyles",
    "GetQuestCategories",
    "GetRecycleTokens",
    "GetSchematics",
    "GetSecurityCameraUUIDById",
    "GetSecurityCameras",
    "GetSellValue_Junkyard",
    "GetSellValue_Junkyard_Scene",
    "GetSellValue_Recycle Center",
    "GetSellValue_River Store",
    "GetSetting",
    "GetSigns",
    "GetSlotLimit",
    "GetSlots",
    "GetStoredStructures",
    "GetTreelineInfo",
    "GetTutorialData",
    "GetUnclaimedQuestRewards",
    "GiftAssignment",
    "HasBasement",
    "HasToolForClassic",
    "HolyGrailGoblinRiddleFailed",
    "ImportMidi",
    "Interact",
    "InventoryAction",
    "IsGoldBombsiteDown",
    "IsTreelineVisible",
    "JoinMyIsland",
    "JoinNewServer",
    "KickPlayer",
    "LinkComponent",
    "LinkPipeComponent",
    "LoadSlot",
    "MoveStructure",
    "MoveStructures",
    "MushroomCaveState",
    "MyIslandSellStuds",
    "NavigateMyIslandPortal",
    "NextMeteor",
    "PlaceAlienQuestOrb",
    "PlaceSchematic",
    "PlayMidiNote",
    "PlaySolo",
    "PlayerJump",
    "Playtest",
    "ProgressHolyGrailDialogue",
    "PropertySelect",
    "PropertySelectNone",
    "PurchasePropertyLocationOffer",
    "QuestlineEntryListRequest",
    "QuestlineListRequest",
    "RefreshSettings",
    "RegisterNoCollide",
    "RegisterNoCollides",
    "RemoveFilterConveyorObject",
    "RemoveItemFromTrade",
    "RemoveStructureFromTrade",
    "RequestContent",
    "RequestDrag",
    "RequestOtherPlayerMoney",
    "ResetCharacter",
    "ResetGiftAssignment",
    "SendDonation",
    "SendDonationMachine",
    "SendTradeRequest",
    "ServerDebugStatus",
    "SetBookCover",
    "SetBounds",
    "SetCommonColor",
    "SetConfirmTradeState",
    "SetCurrencyToTrade",
    "SetEquipmentVisible",
    "SetFilterConveyorBlacklistMode",
    "SetFilterConveyorObjectAllowed",
    "SetFilterConveyorObjectToggled",
    "SetLumberjackArcadeData",
    "SetPermission",
    "SetPlaneBanner",
    "SetPlateText",
    "SetPropertyHole",
    "SetPropertyTerrainStyle",
    "SetRareColor",
    "SetSetting",
    "SetVinylImage",
    "SetWalkingState",
    "SkipTutorialSection",
    "SoftBanPlayer",
    "StartAlienOrbQuest",
    "StartCopperAxeQuest",
    "StartGoblinArenaFlight",
    "StartHolyGrailQuest",
    "StartPondering",
    "StartSecurityCamera",
    "StartVialPuzzle",
    "StopDrag",
    "StopDrone",
    "StopLoadingSlot",
    "StopPondering",
    "StopSecurityCamera",
    "StopTrackingQuest",
    "StoreEquipment",
    "StoreItem",
    "StoreStructure",
    "StoreTool",
    "SubmitBaseReport",
    "SubmitMayorVote",
    "SubmitVote",
    "TakeDamage",
    "TeleportTest",
    "TrackQuest",
    "TransitionNewServer",
    "UnanchorProperty",
    "UnboxPlace",
    "UnlearnBlueprint",
    "UnseatVehicle",
    "UpdateAirshipInfo",
    "UpdateSlotInfo",
    "UseHolyHandGrenade",
    "WMIRegion",
    "WatchDailyRewardAd",
    "WaypointList",
    "WearEquipment",
    "WriteFlag",
    "WritePainting",
    "WriteSignText"
}

-- v119.0
